<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Tdd\Service\CalculadoraService'    => __DIR__ . '/src/Tdd/Service/CalculadoraService.php',
  'Tdd\Module'                        => __DIR__ . '/Module.php',
  'Tdd\Tests\BaseModuleTest'          => __DIR__ . '/tests/Tdd/BaseModuleTest.php',
  'Tdd\Tests\Service\CalculadoraTest' => __DIR__ . '/tests/Tdd/Service/CalculadoraTest.php',
  'Tdd\Tests\ModuleTest'              => __DIR__ . '/tests/Tdd/ModuleTest.php',
  'Tdd\Tests\Bootstrap'               => __DIR__ . '/tests/Bootstrap.php',
);
